### ISSUE TITLE
window.cordova is undefined

### ISSUE THREAD

**Issue by clarkmu** [orchoban/react.cordova#11]
Is "npm start" meant to load with cordova and plugins with hot reloading?  Or do you have to build then inspect?

I've tried reco init on version 1.8 and 2 and it loads on npm start but window.cordova is undefined

**Comment by orchoban** [comment]
Hi, this option does not exist on the older versions (if I remember correctly, from version 1.8 or 2) you probably have a problem with cordova_script.[https://github.com/orchoban/cordova_script]  
Check to see if Port 8597 is free and, if so, reinstall cordova_script
`npm i cordova_script`

**Comment by clarkmu** [comment]
So 'reco serve' should load with window.cordova and plugins?  I tried your troubleshooting tips and it is still not present.  At the end of 'reco init' I get a few "unhandled promise rejections".  Do you have...npm/react/cordova version recommendations?  I'm stuck.

I added cordova to a current React project of mine and got stuck on adding cordova to hot-reload rather than build to browser so thank you for your work!

**Comment by orchoban** [comment]
What's your npm version?   
Let me see the full output of the exception to help you.  
Just copy all the last lines here that you get when you run `reco init <...>`

**Comment by orchoban** [comment]
What is your system? Mac, windows, linux?
