### ISSUE TITLE
Not able to set up

### ISSUE THREAD

**Issue by tirthaguha** [orchoban/react.cordova#16]
CLI doesn't run.

```
C:\WORKSPACE\MOBILE>reco init com.fidelity.hybrid "hello world"
? Please select project template Reco template

---------reco start to build react-app---------
.......reco-cli-init--install-react.cordova-navigation_controller ERROR : Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
reco-cli-init-react ERROR : Error: Command failed: npx create-react-app hello_world
npx: installed 98 in 19.408s
npm ERR! Unexpected end of JSON input while parsing near '...rc.1":"2016-10-04T22:'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[USERNAME]\AppData\Roaming\npm-cache\_logs\2020-05-04T15_31_46_605Z-debug.log

error:  [Error: ENOENT: no such file or directory, open 'C:\WORKSPACE\MOBILE\hello_world\public\index.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\WORKSPACE\\MOBILE\\hello_world\\public\\index.html'
}
C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\react.cordova\bin\reco2\init.js:137
            let dataString = data.toString();
                                  ^

TypeError: Cannot read property 'toString' of undefined
    at ReadFileContext.callback (C:\Users\[USERNAME]\AppData\Roaming\npm\node_modules\react.cordova\bin\reco2\init.js:137:35)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
```

**Comment by orchoban** [comment]
These errors do not belong to this cli.  
It comes from npm i think.  
Please post this as a question in stack-overflow.  
You can tag me so I can help there if needed.

**Comment by fortesp** [comment]
I actually get similar error while initializing a new project.

`
Happy hacking!

reco-cli-init--install-react.cordova-navigation_controller ERROR : Error: Command failed: npm i cordova_script react.cordova-navigation_controller
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: tradingchart@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from cordova_script@1.0.0
npm ERR! node_modules/cordova_script
npm ERR!   cordova_script@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/fortesp/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fortesp/.npm/_logs/2021-06-02T12_53_40_562Z-debug.log

tradingchart/public/index.html ready to by mobile app with cordova
add reco scripts to package.json.

---------reco start to build cordova-app---------

[Error: ENOENT: no such file or directory, scandir 'templates\empty'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'templates\\empty'
}
[Error: ENOENT: no such file or directory, scandir ''] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: ''
}
Creating a new cordova project.
`

**Comment by orchoban** [comment]
Which platform you use? (Windows, Linux, macOS)?
