### ISSUE TITLE
Phonegap build

### ISSUE THREAD

**Issue by 2bsafe** [orchoban/react.cordova#18]
Hey, since i don't have a Mac Product i can't run xcode -> and simply can't build the normal way.

When using PhoneGap build tool iOS works perfectly fine, but my Android version throws an error.

Here's the log file.

https://pastebin.com/ZCmP1GDN

This is my Config.xml:

https://pastebin.com/hcCFsknp

I don't know if this is the way i'm supposed to handle splash screens and icons when having merged cordova and react.

I hope you can help me out so we can release this new build :)

**Comment by orchoban** [comment]
Hi, The product was not built to support PhoneGap. 
Did you try to upload to PhoneGap only the files from `www` folder with `Config.xml` on zip?
Try compiling Android with Cordova on your computer and use PhoneGap for IOS only.
<br/>
<br/>
A good fit of this CLI to PhoneGap will take a lot of development time.
I will try to help you indirectly.

**Comment by orchoban** [comment]
> Hi, The product was not built to support PhoneGap.
> Did you try to upload to PhoneGap only the files from `www` folder with `Config.xml` on zip?
> Try compiling Android with Cordova on your computer and use PhoneGap for IOS only.
> 
> 
> 
> 
> A good fit of this CLI to PhoneGap will take a lot of development time.
> I will try to help you indirectly.

@2bsafe Let me know if it's work for you.
