### ISSUE TITLE
What is the workflow in git for project created with this package?

### ISSUE THREAD

**Issue by amitznati** [orchoban/react.cordova#22]
Hi,
Awesome package!
(; כל הכבוד
Please advise what is the workflow for project created with this library,
i saw that the _platforms_ and _plugins_ folder are ignored by default in git,
so after i pushed project to git and cloned it in other PC how do i generate those folders again?

**Comment by orchoban** [comment]
Hi, thank.

Try:
https://stackoverflow.com/a/29972835/9536897
I hope it will help.  
The cause of your problem comes from Cordova.

**Comment by amitznati** [comment]
Worked!
Thank you!
