### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by klebersm** [orchoban/react.cordova#23]
Is possible change port 3000 at 'reco serve'?
I already tried some ways, but no success.

**Comment by orchoban** [comment]
Sorry but not. 
You can try add it by yourself and pull-reqest to this project

**Comment by gach87** [comment]
Hi. You can try adding to the package.json start script, the environment variable PORT. It worked for me @klebersm .

`  
"scripts": {
    "start": "PORT=3019 reco serve"}
`
