### ISSUE TITLE
First install

### ISSUE THREAD

**Issue by stempora** [orchoban/react.cordova#29]
Hello,

After installing and creating the first app, when starting ( npm start ) i get the following:

```
./src/index.js
Module not found: Can't resolve 'cordova_script' in 'f:\test\hello_world\src'
```

**Comment by orchoban** [comment]
Hi, this is not issue for this CLI.
This is from react code.
Please write questions on [stackoverflow](https://stackoverflow.com/), you can write link to stackoverflow here and I will try to help you.

**Comment by orchoban** [comment]
Try `npm i cordova_script`
https://www.npmjs.com/package/cordova_script

**Comment by orchoban** [comment]
@stempora let me know

**Comment by stempora** [comment]
Hi,

yes that fixed that part, thanks a lot, now trying to fix other incompatibilities between packages :)

**Comment by orchoban** [comment]
@stempora try `npm i`
