### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by abdellahFihri** [orchoban/react.cordova#5]
hi, when i try to run reco build i get this error:
reco start to build cordova

Checking Java JDK and Android SDK versions

ANDROID_SDK_ROOT=undefined (reactmmended setting)
ANDROID_HOME=C:\Users\abdel\AppData\Local\Android\sdk (DEPRECATED)

reco-cli-build-cordova ERROR : Error: Command failed: cordova build
Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle
in your path, or install Android Studio
 knowing that i installed all of them can you please help? thank you in advance

**Comment by MickeyShalev** [comment]
I happened to me as well after updating Android studio.
I solved it by downloading Gradle manually and adding it to  system variables and to system path (don't forger to restart your computer).
You can find more information here : https://gradle.org/install/

![image](https://user-images.githubusercontent.com/20965043/69004800-936a2800-0921-11ea-933c-b31e245ecc19.png)

**Comment by orchoban** [comment]
You have to set ANDROID_SDK_ROOT instead.

1. Open control panel
2. Then go to System
3. Then go to Change Environment Variables of the User
4. Then click create a new environment variables
5. Create a new variable named ANDROID_SDK_HOME
6. Set its value to your Android directory C:\Users\...\AppData\Local\Android\sdk
