### ISSUE TITLE
Have to manually yarn install after reco init

### ISSUE THREAD

**Issue by wizevlad** [orchoban/react.cordova#7]
When doing
```
reco init ...
```
Gives error: 
```
Plugin dependency "cordova-plugin-badge@0.8.8" already fetched, using that version.
Installing "cordova-plugin-badge" for ios
Adding cordova-plugin-local-notification to package.json

reco-react-cli ERROR : Error: Command failed: npm run build
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-js@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-js@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladimir.lopez/.npm/_logs/2019-12-03T17_55_54_328Z-debug.log

./HelloCamera/react-js/public/index.html ready to by mobile app with cordova
updete homepage in react-js package.json , now it's ready to by mobile app with cordova.
```

There is also a typo: `updete -> update`
Had to manually `cd react-js && yarn install`

**Comment by datnordstrom** [comment]
<img width="393" alt="Screen Shot 2019-12-03 at 10 55 42 AM" src="https://user-images.githubusercontent.com/13420412/70080509-8739c800-15bb-11ea-9ade-9487762f25d3.png">
Related.

**Comment by orchoban** [comment]
Thank you for your response.
Are you adding the plugin cordova-plugin-badge?
Did the error appear in the first run of `reco init ..`?
Did you choose a project including Template?
What is your running platform?


> <img alt="Screen Shot 2019-12-03 at 10 55 42 AM" width="393" src="https://user-images.githubusercontent.com/13420412/70080509-8739c800-15bb-11ea-9ade-9487762f25d3.png">
> 
> Related.

Hi, I need to see the full path.

Did it arrive at `npm start`?
If not, try running `npm start` and update me please what is the response

**Comment by orchoban** [comment]
> <img alt="Screen Shot 2019-12-03 at 10 55 42 AM" width="393" src="https://user-images.githubusercontent.com/13420412/70080509-8739c800-15bb-11ea-9ade-9487762f25d3.png">
> 
> Related.

Hi, I need to see the full path.

Did it arrive at `npm start`?
If not, try running `npm start` and update me please what is the response

**Comment by orchoban** [comment]
What is your `reco` version?

**Comment by datnordstrom** [comment]
It's the latest version, and this error goes away after manually doing: `cd react-js && yarn install`

**Comment by orchoban** [comment]
try to run `reco start` or `npm start` In the main dir.
Let me know if there is a react output

**Comment by datnordstrom** [comment]
It just gives a Module not found error in the browser view.

**Comment by orchoban** [comment]
> Thank you for your response.
> Are you adding the plugin cordova-plugin-badge?
> Did the error appear in the first run of `reco init ..`?
> Did you choose a project including Template?
> What is your running platform?
> 
> The error came from react, try running `npm start`

@wizevlad , let me know

**Comment by wizevlad** [comment]
Yes
Yes
No
Mac

I also still don't know how to do live reload from within the iOS emulator

**Comment by orchoban** [comment]
Try the new version <2.0.0.
`npm i -g react.cordova`
  Then start a new project.
`reco init com.myId my-app-name`
