### ISSUE TITLE
Babel?

### ISSUE THREAD

**Issue by datnordstrom** [orchoban/react.cordova#8]
I tried to add react-id-swiper and got a babel error.

**Comment by orchoban** [comment]
What's your reco version?
Please check if that plugin was added to ./package.json or to ./react-js/package.json
and let me know.

**Comment by orchoban** [comment]
You must run `reco install <npmjs-package-for-react>` or `reco i <npmjs-package-for-react>` and not `npm install  <...>`

**Comment by orchoban** [comment]
Try the new version <2.0.0.
`npm i -g react.cordova`
  Then start a new project.
`reco init com.myId my-app-name`
