### ISSUE TITLE
running npm run build - cordova error

### ISSUE THREAD

**Issue by arkadi-luder** [orchoban/react.cordova#9]
The error:

> Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
...
> npm ERR! com.example.hello@1.0.0 build: `react-scripts build && reco copy && cordova build`

**Comment by arkadi-luder** [comment]
Was able to sort this by using cordova version 8.1.2

Just run: `npm install -g cordova@8.1.2`

**Comment by arkadi-luder** [comment]
Next error presented is:

> Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.

**Comment by orchoban** [comment]
> Was able to sort this by using cordova version 8.1.2
> 
> Just run: `npm install -g cordova@8.1.2`

https://stackoverflow.com/a/58956882/9536897
